# Format: RequestClass=ResponseClass:field1=field1Response,field2=field2Response,field3=field3Response

UserResponse=UserResponse:username=username,role=role,name=name
CreateAccountResponse=AccountsResponse:id=id,accountNumber=accountNumber,balance=balance
AccountResponse=AccountResponse:id=id,accountNumber=accountNumber,balance=balance
CreateUserRequest=UserResponse:username=username,role=role